### PR TITLE
General fixes to the recipe pages

### PR DESCRIPTION
**Pull request by alkyaly**
- Grammar fixes
- Move type creation to its own page
- Improved explanation in some places

Hopefully it's a bit better now.

### CODE REVIEW

**Review by OroArmor — CHANGES_REQUESTED** [review]
Looks great and the clarifications are perfect. I might add some more information about recipes via json and how they are usually unlocked with advancements. A link to a generator and the wiki would also be great.

**Comment by gdude2002** [comment]
Has there been any movement on this? It's been over three weeks since the last activity.

**Comment by alkyaly** [comment]
> A link to a generator and the wiki would also be great
Done

> Has there been any movement on this?
I kinda had forgotten 😅

**Review by OroArmor — APPROVED** [review]

**Review by Mysterious-Dev — APPROVED** [review]

**Comment by gdude2002** [comment]
Thanks, 🚀

**Pull request merged**
