### PR TITLE
Add github actions & fix build errors

### PR DESCRIPTION
**Pull request by anonymous123-code**
- Adds commit preview and PR preview github actions
- Fixes build erroring

Notes:
- Requires CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_API_TOKEN secrets to be set
- Requires COZY_PAT token with write access to this repository
- Requires rewrite to be the default branch for PR previews to work
- Currently the rewrite preview on the rewrite branch is done through cloudflare's git integration, it might be needed to switch to manual upload (might work without doing this)

### CODE REVIEW

**Comment by Southpaw1496** [comment]
> Requires CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_API_TOKEN secrets to be set
Requires COZY_PAT token with write access to this repository
I have done this

> Currently the rewrite preview on the rewrite branch is done through cloudflare's git integration, it might be needed to switch to manual upload (might work without doing this)

I'm pretty sure it won't, I'll set this up now.

**Review by OroArmor — CHANGES_REQUESTED** [review]
Could you also reintroduce the action that publishes the commit? https://github.com/QuiltMC/developer-wiki/blob/old/.github/workflows/publish.yml
and probably the issue templates too since i think those are gone now

**Comment by Akarys42** [comment]
> Could you also reintroduce the action that publishes the commit? https://github.com/QuiltMC/developer-wiki/blob/old/.github/workflows/publish.yml and probably the issue templates too since i think those are gone now

Those actions are copied from the website (which I've wrote). Commit preview is already included, Cozy will even drop a comment on the commit linking to the preview.

**Comment by Akarys42** [comment]
Please also note the project needs to be deleted and recreated as a manual upload (you can just put a dummy file in), and the custom domain relinked. It will fail otherwise.

It does mean the preview URL in any existing PR will have to be changed, as well as the main branch pulled in for the whole integration to continue working correctly.

**Comment by Southpaw1496** [comment]
I asked on the Cloudflare Discord and the person I spoke too said it would Just Work™️

**Comment by Akarys42** [comment]
> I asked on the Cloudflare Discord and the person I spoke too said it would Just Work™️

That's interesting, although you'd still want the default integration to disappear, which I believe you need to recreate the project for that? I didn't know that though, that's cool.

**Review by OroArmor — APPROVED** [review]

**Pull request merged**
