### PR TITLE
Tabs to display multiple languages

### PR DESCRIPTION
**Pull request by lukebemish**
This PR provides a system for displaying code samples from multiple different JVM languages for the same thing. The syntax it uses is as follows:

~~~markdown
```tabbed-files
java:path/to/java/file.java@Region
kotlin:path/to/kotlin/file.kt@Region
```
~~~

Much as with the old system, the `@Region` section is optional. The old system for specifying code samples still works, and was improved slightly as well - it now allows for a sample to be color-coded using a language identifier that doesn't match the file extension. (this is useful for, for example, kotlin files that are `.kt`, among others). The extended format now allows:
~~~markdown
```language:path/to/file.ext@Region
```
~~~
If `language` is `file` (the old format), then the language is taken from the file extension as before.

Some other minor changes were made as well. Notably:
 * removed the extra newline after the `// ...` at the end of region samples that made them look a bit weird (if there's a reason for that that I'm not aware of, it could be readded)
 * Added a system that trims spaces from the starts of each line in code blocks so that they're more readable on smaller screens when the region they were sampled from is uniformly indented

Some screenshots of the tab system:
image
image

(Note: this PR has an accompanying PR QuiltMC/quilt-bulma#8 to make some style changes necessary for bulma tabs to render correctly. If you're testing locally, the style won't look right at all unless you use the generated CSS files from that branch)

### CODE REVIEW

**Comment by lukebemish** [comment]
An example of a block after my spacing and extra-newline-removal changes:
image

**Comment by lukebemish** [comment]
Oh, heh, nearly forgot something I changed that I could revert if necessary: I did `chmod +x` on `gradlew`. That might be something to revert and do in another PR, but it should probably be done at some point for the sake of all us folks who use the terminal a lot, since we can't really invoke gradle from the terminal as easily without doing that. Let me know if you want me to keep that in or remove it

**Review by OroArmor — APPROVED** [review]

**Comment by gdude2002** [comment]
Why did you merge this immediately?

**Comment by OroArmor** [comment]
since the only thing holding it back was the css

**Comment by gdude2002** [comment]
Which you don't have

**Pull request merged**
