### PR TITLE
switch from svelte-i18n to svelte-fluent

### LINKED ISSUE #18: Multilingual support
**What would you like the wiki to cover?**
I hope that the wiki can have more languages.

**Why should this be added to the wiki?**
To make more people easier to read the docs.

**Where in the wiki should this go?**
It may put in footer or the right up corner.
I recommend use crowdin for community translating.

### PR DESCRIPTION
**Pull request by c-leri**
Advantages:
- Nicer interpolation
  - more explicit (named values)
  - allows to interpolates multiples values per string
- No need for svelte-markdown for links/markup thanks to Overlays
- Translations now fallback to the user's other prefered languages if a key is missing in its main language before defaulting to english
- Arguably easier to understand and work with

Disadvantages:
- Maybe the translations keys are less clear ? since they can't be nested into groups

Edit: Some level of nesting is possible with attributes

Edit: I think that this should close #18 with the rtl support and all

### CODE REVIEW

**Review by OroArmor — APPROVED** [review]
Looks good!

**Comment by c-leri** [comment]
Now when a wiki article isn't available in the current locale it will fallback to the user's first available locale instead of just redirecting to the english version (a message is still displayed explaining why the article isn't in their choosen language)

**Comment by c-leri** [comment]
Yes I think that I covered everything now !

**Review by ix0rai — APPROVED** [review]
will be good to merge once merge conflicts are fixed and I do some testing!

**Comment by c-leri** [comment]
Merge conflicts resolved :+1:

**Comment by c-leri** [comment]
Also I noticed that now the translations keys of categories names and articles titles are pretty much always just the same as their slug. So I'm wondering if we should remove them and just use the slugs instead, or keep them for the sake of clarity or in case it becomes useful again later down the line ?

**Comment by ix0rai** [comment]
i think using the slugs would be nice, I don't see an advantage to manually defining them

**Comment by c-leri** [comment]
Done :+1:

**Comment by c-leri** [comment]
I add an idea to decomplexify the article loading process so im marking this as a draft pr for now

**Comment by c-leri** [comment]
That's done!
The available locales for articles are now calculated at compile time which makes it possible to no longer rely on error for control flow when loading the content of an article at run time.
This should probably also make this somewhat faster in some extreme cases since we no longer try to load articles in different locales until we find something that works.

**Comment by ix0rai** [comment]
great work here!

**Pull request merged**
